package ru.poporyadku.ui.theme

import androidx.compose.ui.graphics.Color

// DESIGN_TOKENS.md §6.2 — светлая тема. Значения перенесены буквально, один в один.
val PrimaryLight = Color(0xFF2C4A3E)
val OnPrimaryLight = Color(0xFFF6F0E2)
val PrimaryContainerLight = Color(0xFFE4E9DE)
val OnPrimaryContainerLight = Color(0xFF2C4A3E)
val SecondaryLight = Color(0xFF55665C)
val OnSecondaryLight = Color(0xFFF6F0E2)
val SecondaryContainerLight = Color(0xFFDCE3DC)
val OnSecondaryContainerLight = Color(0xFF33413A)
val TertiaryLight = Color(0xFF9C4A2E)
val OnTertiaryLight = Color(0xFFF6F0E2)
val TertiaryContainerLight = Color(0xFFF2DDD2)
val OnTertiaryContainerLight = Color(0xFF6B2F1C)
val ErrorLight = Color(0xFFA3342E)
val OnErrorLight = Color(0xFFF6F0E2)
val ErrorContainerLight = Color(0xFFF5DAD5)
val OnErrorContainerLight = Color(0xFF6B211B)
val BackgroundLight = Color(0xFFF6F0E2)
val OnBackgroundLight = Color(0xFF23241F)
val SurfaceLight = Color(0xFFF6F0E2)
val OnSurfaceLight = Color(0xFF23241F)
val SurfaceVariantLight = Color(0xFFEFE6D2)
val OnSurfaceVariantLight = Color(0xFF5B584C)
val SurfaceTintLight = PrimaryLight
val InverseSurfaceLight = Color(0xFF33312A)
val InverseOnSurfaceLight = Color(0xFFF2ECDC)
val InversePrimaryLight = Color(0xFF8FB5A2)
val OutlineLight = Color(0xFF8C8672)
val OutlineVariantLight = Color(0xFFDCD3BC)
val ScrimLight = Color(0xFF000000)
val SurfaceBrightLight = Color(0xFFFDFBF5)
val SurfaceDimLight = Color(0xFFE4DCC5)
val SurfaceContainerLowestLight = Color(0xFFFBF8F0)
val SurfaceContainerLowLight = Color(0xFFFBF7EC)
val SurfaceContainerLight = Color(0xFFF5EFE0)
val SurfaceContainerHighLight = Color(0xFFEFE6CE)
val SurfaceContainerHighestLight = Color(0xFFE9DFC0)

// DESIGN_TOKENS.md §6.2 — тёмная тема. Не инверсия — независимо переопределённые роли.
val PrimaryDark = Color(0xFF3E6350)
val OnPrimaryDark = Color(0xFFF5EFE0)
val PrimaryContainerDark = Color(0xFF24352C)
val OnPrimaryContainerDark = Color(0xFFCFE0D2)
val SecondaryDark = Color(0xFF8FA398)
val OnSecondaryDark = Color(0xFF16261E)
val SecondaryContainerDark = Color(0xFF2B3A32)
val OnSecondaryContainerDark = Color(0xFFCDDCD2)
val TertiaryDark = Color(0xFFD68A63)
val OnTertiaryDark = Color(0xFF3A2013)
val TertiaryContainerDark = Color(0xFF4A2A1E)
val OnTertiaryContainerDark = Color(0xFFF0C9B3)
val ErrorDark = Color(0xFFE8998C)
val OnErrorDark = Color(0xFF3B0E09)
val ErrorContainerDark = Color(0xFF5C231C)
val OnErrorContainerDark = Color(0xFFF5CCC4)
val BackgroundDark = Color(0xFF1C1A16)
val OnBackgroundDark = Color(0xFFEDE7D8)
val SurfaceDark = Color(0xFF1C1A16)
val OnSurfaceDark = Color(0xFFEDE7D8)
val SurfaceVariantDark = Color(0xFF3A3527)
val OnSurfaceVariantDark = Color(0xFFB9B2A0)
val SurfaceTintDark = PrimaryDark
val InverseSurfaceDark = Color(0xFFEDE4CE)
val InverseOnSurfaceDark = Color(0xFF2C2A22)
val InversePrimaryDark = Color(0xFF2C4A3E)
val OutlineDark = Color(0xFF8A8370)
val OutlineVariantDark = Color(0xFF3C382C)
val ScrimDark = Color(0xFF000000)
val SurfaceBrightDark = Color(0xFF3A3527)
val SurfaceDimDark = Color(0xFF141210)
val SurfaceContainerLowestDark = Color(0xFF111008)
val SurfaceContainerLowDark = Color(0xFF262319)
val SurfaceContainerDark = Color(0xFF2C2820)
val SurfaceContainerHighDark = Color(0xFF332E24)
val SurfaceContainerHighestDark = Color(0xFF3A3428)

// DESIGN_TOKENS.md §6.2 — Fixed-роли: одинаковы в обеих темах.
val PrimaryFixed = Color(0xFFE4E9DE)
val PrimaryFixedDim = Color(0xFFB6C1B6)
val OnPrimaryFixed = Color(0xFF2C4A3E)
val OnPrimaryFixedVariant = Color(0xFF3D5147)
val SecondaryFixed = Color(0xFFDCE3DC)
val SecondaryFixedDim = Color(0xFFB4BEB6)
val OnSecondaryFixed = Color(0xFF33413A)
val OnSecondaryFixedVariant = Color(0xFF414C45)
val TertiaryFixed = Color(0xFFF2DDD2)
val TertiaryFixedDim = Color(0xFFDFBDAE)
val OnTertiaryFixed = Color(0xFF6B2F1C)
val OnTertiaryFixedVariant = Color(0xFF734235)
